apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      {{- include "wiki-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fastapi
  template:
    metadata:
      labels:
        {{- include "wiki-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.fastapi.image_name }}
        imagePullPolicy: {{ .Values.fastapi.imagePullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: {{ .Values.fastapi.containerPort }}
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "wiki-chart.fullname" . }}-db-secret
              key: database-url
        resources:
          {{- toYaml .Values.fastapi.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5

